# 作業 : (Kaggle)鐵達尼生存預測
***
- 分數以網站評分結果為準, 請同學實際將提交檔(*.csv)上傳試試看  
https://www.kaggle.com/c/titanic/submit

# [作業目標]
- 試著模仿範例寫法, 在鐵達尼生存預測中, 觀察觀查混合泛化 (Blending) 的寫法與效果

# [作業重點]
- 觀察混合泛化的準確度 (In[14]), 是否比單一模型準確度為高 (In[11~13])  
- 除了我們的權重, 同學也可以試著自行調整權重 (注意:權重和=1), 看看有什麼影響
- Hint : 除了權重, 分類預測的調整, 還可以調整什麼地方?

In [1]:
# 做完特徵工程前的所有準備 (與前範例相同)
import pandas as pd
import numpy as np
import copy, time
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

data_path = 'data/'
df_train = pd.read_csv('http://ai100.cupoy.com/file-download/part02/titanic_train.csv')
df_test = pd.read_csv('http://ai100.cupoy.com/file-download/part02/titanic_test.csv')

train_Y = df_train['Survived']
ids = df_test['PassengerId']
df_train = df_train.drop(['PassengerId', 'Survived'] , axis=1)
df_test = df_test.drop(['PassengerId'] , axis=1)
df = pd.concat([df_train,df_test])
df.head()

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# 檢查 DataFrame 空缺值的狀態
def na_check(df_data):
    data_na = (df_data.isnull().sum() / len(df_data)) * 100
    data_na = data_na.drop(data_na[data_na == 0].index).sort_values(ascending=False)
    missing_data = pd.DataFrame({'Missing Ratio' :data_na})
    display(missing_data.head(10))
na_check(df)

          Missing Ratio
Cabin         77.463713
Age           20.091673
Embarked       0.152788
Fare           0.076394

In [3]:
# 以下 In[3]~In[10] 只是鐵達尼預測中的一組特徵工程, 並以此組特徵工程跑參數, 若更換其他特徵工程, In[10]的參數需要重新跑
# Sex : 直接轉男 0 女 1
df["Sex"] = df["Sex"].map({"male": 0, "female":1})
# Fare : 用 log 去偏態, 0 則直接取 0
df["Fare"] = df["Fare"].map(lambda i: np.log(i) if i > 0 else 0)
# Age : 缺值用中位數補
df["Age"] = df["Age"].fillna(df['Age'].median())

In [4]:
# Title 的 特徵工程 : 將各種頭銜按照類型分類, 最後取 One Hot
df_title = [i.split(",")[1].split(".")[0].strip() for i in df["Name"]]
df["Title"] = pd.Series(df_title)
df["Title"] = df["Title"].replace(['Lady', 'the Countess','Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
df["Title"] = df["Title"].map({"Master":0, "Miss":1, "Ms" : 1 , "Mme":1, "Mlle":1, "Mrs":1, "Mr":2, "Rare":3})
df["Title"] = df["Title"].astype(int)
df = pd.get_dummies(df, columns = ["Title"])

In [5]:
# 新建:家庭大小 (Fsize)特徵, 並依照大小分別建獨立欄位
df["Fsize"] = df["SibSp"] + df["Parch"] + 1
df['Single'] = df['Fsize'].map(lambda s: 1 if s == 1 else 0)
df['SmallF'] = df['Fsize'].map(lambda s: 1 if  s == 2  else 0)
df['MedF'] = df['Fsize'].map(lambda s: 1 if 3 <= s <= 4 else 0)
df['LargeF'] = df['Fsize'].map(lambda s: 1 if s >= 5 else 0)

In [6]:
# Ticket : 如果不只是數字-取第一個空白之前的字串(去除'.'與'/'), 如果只是數字-設為'X', 最後再取 One Hot
Ticket = []
for i in list(df.Ticket):
    if not i.isdigit() :
        Ticket.append(i.replace(".","").replace("/","").strip().split(' ')[0])
    else:
        Ticket.append("X")        
df["Ticket"] = Ticket
df = pd.get_dummies(df, columns = ["Ticket"], prefix="T")

In [7]:
# Cabib 依照第一碼分類, 再取 One Hot
df["Cabin"] = pd.Series([i[0] if not pd.isnull(i) else 'X' for i in df['Cabin'] ])
df = pd.get_dummies(df, columns = ["Cabin"], prefix="Cabin")

In [8]:
# Embarked, Pclass 取 One Hot
df = pd.get_dummies(df, columns = ["Embarked"], prefix="Em")
df["Pclass"] = df["Pclass"].astype("category")
df = pd.get_dummies(df, columns = ["Pclass"], prefix="Pc")

# 捨棄 Name 欄位
df.drop(labels = ["Name"], axis = 1, inplace = True)

In [9]:
# 確認缺值 與 目前的資料表內容
na_check(df)
df.head()

Empty DataFrame
Columns: [Missing Ratio]
Index: []

,Sex,Age,SibSp,Parch,Fare,Title_0,Title_1,Title_2,Title_3,Fsize,...,Cabin_F,Cabin_G,Cabin_T,Cabin_X,Em_C,Em_Q,Em_S,Pc_1,Pc_2,Pc_3
0,0,22.0,1,0,1.981001,0,0,1,0,2,...,0,0,0,1,0,0,1,0,0,1
1,1,38.0,1,0,4.266662,0,1,0,0,2,...,0,0,0,0,1,0,0,1,0,0
2,1,26.0,0,0,2.070022,0,1,0,0,1,...,0,0,0,1,0,0,1,0,0,1
3,1,35.0,1,0,3.972177,0,1,0,0,2,...,0,0,0,0,0,0,1,1,0,0
4,0,35.0,0,0,2.085672,0,0,1,0,1,...,0,0,0,1,0,0,1,0,0,1

In [10]:
# 將資料最大最小化
df = MinMaxScaler().fit_transform(df)

# 將前述轉換完畢資料 df , 重新切成 train_X, test_X
train_num = train_Y.shape[0]
train_X = df[:train_num]
test_X = df[train_num:]

# 使用三種模型 : 邏輯斯迴歸 / 梯度提升機 / 隨機森林, 參數使用 Random Search 尋找
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
lr = LogisticRegression(tol=0.001, penalty='l2', fit_intercept=True, C=1.0)
gdbt = GradientBoostingClassifier(tol=100, subsample=0.75, n_estimators=250, max_features=20,
                                  max_depth=6, learning_rate=0.03)
rf = RandomForestClassifier(n_estimators=100, min_samples_split=2, min_samples_leaf=1, 
                            max_features='sqrt', max_depth=6, bootstrap=True)

In [11]:
# 線性迴歸預測檔 (結果有部分隨機, 請以 Kaggle 計算的得分為準, 以下模型同理)
lr.fit(train_X, train_Y)

lr_pred = lr.predict_proba(test_X)[:,1]
ls_score=lr.score(train_X,train_Y)
print(ls_score)
sub = pd.DataFrame({'PassengerId': ids, 'Survived': lr_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_lr.csv', index=False)

[[0.91659786 0.08340214]
 [0.44386733 0.55613267]
 [0.48277928 0.51722072]
 [0.57641132 0.42358868]
 [0.79417158 0.20582842]
 [0.91425513 0.08574487]
 [0.42476809 0.57523191]
 [0.18726429 0.81273571]
 [0.24513817 0.75486183]
 [0.70436357 0.29563643]
 [0.69205958 0.30794042]
 [0.28235127 0.71764873]
 [0.47132697 0.52867303]
 [0.90965653 0.09034347]
 [0.25381701 0.74618299]
 [0.12925889 0.87074111]
 [0.17066581 0.82933419]
 [0.88465531 0.11534469]
 [0.45601631 0.54398369]
 [0.32945774 0.67054226]
 [0.79948188 0.20051812]
 [0.70369568 0.29630432]
 [0.13631196 0.86368804]
 [0.53604207 0.46395793]
 [0.4456089  0.5543911 ]
 [0.79215063 0.20784937]
 [0.34907097 0.65092903]
 [0.84859518 0.15140482]
 [0.33111544 0.66888456]
 [0.89065464 0.10934536]
 [0.81942341 0.18057659]
 [0.22670689 0.77329311]
 [0.38743744 0.61256256]
 [0.90371311 0.09628689]
 [0.68115716 0.31884284]
 [0.88067448 0.11932552]
 [0.80606672 0.19393328]
 [0.786408   0.213592  ]
 [0.64486014 0.35513986]
 [0.57543929 0.42456071]
 [0.62266438 0.37733562]
 [0.29398001 0.70601999]
 [0.93667419 0.06332581]
 [0.18500942 0.81499058]
 [0.16441534 0.83558466]
 [0.70468072 0.29531928]
 [0.74256754 0.25743246]
 [0.59048713 0.40951287]
 [0.42107674 0.57892326]
 [0.3789481  0.6210519 ]
 [0.13678945 0.86321055]
 [0.74432015 0.25567985]
 [0.06511641 0.93488359]
 [0.47652728 0.52347272]
 [0.5612098  0.4387902 ]
 [0.98013926 0.01986074]
 [0.68674649 0.31325351]
 [0.92896665 0.07103335]
 [0.69937845 0.30062155]
 [0.0250864  0.9749136 ]
 [0.91999389 0.08000611]
 [0.25128231 0.74871769]
 [0.8932606  0.1067394 ]
 [0.12347362 0.87652638]
 [0.91866813 0.08133187]
 [0.045558   0.954442  ]
 [0.16997651 0.83002349]
 [0.77895752 0.22104248]
 [0.20965408 0.79034592]
 [0.90050421 0.09949579]
 [0.74180033 0.25819967]
 [0.63883343 0.36116657]
 [0.80891185 0.19108815]
 [0.69412379 0.30587621]
 [0.2900349  0.7099651 ]
 [0.41007021 0.58992979]
 [0.93132637 0.06867363]
 [0.61209722 0.38790278]
 [0.20552305 0.79447695]
 [0.29360473 0.70639527]
 [0.85363678 0.14636322]
 [0.85816583 0.14183417]
 [0.3658212  0.6341788 ]
 [0.93156081 0.06843919]
 [0.35223821 0.64776179]
 [0.59426794 0.40573206]
 [0.74992351 0.25007649]
 [0.83479216 0.16520784]
 [0.23989438 0.76010562]
 [0.76734594 0.23265406]
 [0.82214304 0.17785696]
 [0.93174717 0.06825283]
 [0.22064375 0.77935625]
 [0.93132637 0.06867363]
 [0.62994036 0.37005964]
 [0.92872979 0.07127021]
 [0.51455962 0.48544038]
 [0.44582467 0.55417533]
 [0.34827806 0.65172194]
 [0.94376454 0.05623546]
 [0.10435687 0.89564313]
 [0.85289586 0.14710414]
 [0.759638   0.240362  ]
 [0.92977111 0.07022889]
 [0.69944875 0.30055125]
 [0.84478202 0.15521798]
 [0.56388129 0.43611871]
 [0.90881631 0.09118369]
 [0.93035994 0.06964006]
 [0.38307998 0.61692002]
 [0.72195904 0.27804096]
 [0.30633147 0.69366853]
 [0.43205541 0.56794459]
 [0.27878899 0.72121101]
 [0.20148018 0.79851982]
 [0.89674824 0.10325176]
 [0.89720102 0.10279898]
 [0.63459502 0.36540498]
 [0.42160044 0.57839956]
 [0.18836963 0.81163037]
 [0.53120056 0.46879944]
 [0.9309406  0.0690594 ]
 [0.41414955 0.58585045]
 [0.31870606 0.68129394]
 [0.759638   0.240362  ]
 [0.16487302 0.83512698]
 [0.9256246  0.0743754 ]
 [0.74451324 0.25548676]
 [0.32543254 0.67456746]
 [0.9272987  0.0727013 ]
 [0.93369199 0.06630801]
 [0.71987247 0.28012753]
 [0.8045293  0.1954707 ]
 [0.6306901  0.3693099 ]
 [0.94484616 0.05515384]
 [0.92761319 0.07238681]
 [0.27682624 0.72317376]
 [0.77471619 0.22528381]
 [0.77394084 0.22605916]
 [0.98263798 0.01736202]
 [0.82192539 0.17807461]
 [0.09007478 0.90992522]
 [0.76196434 0.23803566]
 [0.81318916 0.18681084]
 [0.78105133 0.21894867]
 [0.94228347 0.05771653]
 [0.71708613 0.28291387]
 [0.65110214 0.34889786]
 [0.60931481 0.39068519]
 [0.75669435 0.24330565]
 [0.24446401 0.75553599]
 [0.46451226 0.53548774]
 [0.97072907 0.02927093]
 [0.81801632 0.18198368]
 [0.9905277  0.0094723 ]
 [0.96992885 0.03007115]
 [0.09972194 0.90027806]
 [0.79456525 0.20543475]
 [0.78105133 0.21894867]
 [0.14477389 0.85522611]
 [0.7534475  0.2465525 ]
 [0.46144145 0.53855855]
 [0.59436155 0.40563845]
 [0.93300391 0.06699609]
 [0.23442816 0.76557184]
 [0.15650928 0.84349072]
 [0.08453737 0.91546263]
 [0.96664478 0.03335522]
 [0.35050946 0.64949054]
 [0.78789397 0.21210603]
 [0.93818941 0.06181059]
 [0.29818192 0.70181808]
 [0.68902635 0.31097365]
 [0.89515246 0.10484754]
 [0.98559382 0.01440618]
 [0.51157572 0.48842428]
 [0.05222996 0.94777004]
 [0.24321605 0.75678395]
 [0.60720327 0.39279673]
 [0.50173654 0.49826346]
 [0.42551404 0.57448596]
 [0.69828203 0.30171797]
 [0.04337165 0.95662835]
 [0.21438535 0.78561465]
 [0.0667871  0.9332129 ]
 [0.75015499 0.24984501]
 [0.36405173 0.63594827]
 [0.95020063 0.04979937]
 [0.98298411 0.01701589]
 [0.85648899 0.14351101]
 [0.48288997 0.51711003]
 [0.74290631 0.25709369]
 [0.63264276 0.36735724]
 [0.14245997 0.85754003]
 [0.16907382 0.83092618]
 [0.48505049 0.51494951]
 [0.4907505  0.5092495 ]
 [0.78209731 0.21790269]
 [0.40610029 0.59389971]
 [0.37516932 0.62483068]
 [0.72811827 0.27188173]
 [0.89157522 0.10842478]
 [0.7321329  0.2678671 ]
 [0.51986744 0.48013256]
 [0.82974783 0.17025217]
 [0.28364402 0.71635598]
 [0.7727665  0.2272335 ]
 [0.8294395  0.1705605 ]
 [0.09731542 0.90268458]
 [0.87184208 0.12815792]
 [0.85265473 0.14734527]
 [0.64149134 0.35850866]
 [0.82876617 0.17123383]
 [0.74665676 0.25334324]
 [0.98394386 0.01605614]
 [0.13018046 0.86981954]
 [0.30581649 0.69418351]
 [0.77782115 0.22217885]
 [0.02535205 0.97464795]
 [0.93132637 0.06867363]
 [0.5620188  0.4379812 ]
 [0.92413625 0.07586375]
 [0.77219204 0.22780796]
 [0.92456218 0.07543782]
 [0.42012947 0.57987053]
 [0.70152498 0.29847502]
 [0.92667325 0.07332675]
 [0.75337142 0.24662858]
 [0.93501083 0.06498917]
 [0.44814073 0.55185927]
 [0.23367921 0.76632079]
 [0.44207121 0.55792879]
 [0.94493506 0.05506494]
 [0.58972798 0.41027202]
 [0.7508459  0.2491541 ]
 [0.63552079 0.36447921]
 [0.77384246 0.22615754]
 [0.52214891 0.47785109]
 [0.59010758 0.40989242]
 [0.49561157 0.50438843]
 [0.105635   0.894365  ]
 [0.20145705 0.79854295]
 [0.65124163 0.34875837]
 [0.93157354 0.06842646]
 [0.96837807 0.03162193]
 [0.6524709  0.3475291 ]
 [0.11084048 0.88915952]
 [0.45208379 0.54791621]
 [0.36748939 0.63251061]
 [0.66095795 0.33904205]
 [0.50318327 0.49681673]
 [0.6863815  0.3136185 ]
 [0.55299391 0.44700609]
 [0.92539455 0.07460545]
 [0.67073511 0.32926489]
 [0.6621698  0.3378302 ]
 [0.58473529 0.41526471]
 [0.46477095 0.53522905]
 [0.16091689 0.83908311]
 [0.63950842 0.36049158]
 [0.94750971 0.05249029]
 [0.38210082 0.61789918]
 [0.251176   0.748824  ]
 [0.55349308 0.44650692]
 [0.31160449 0.68839551]
 [0.93156081 0.06843919]
 [0.84285242 0.15714758]
 [0.93126377 0.06873623]
 [0.29545876 0.70454124]
 [0.53860767 0.46139233]
 [0.65751059 0.34248941]
 [0.90881631 0.09118369]
 [0.07031957 0.92968043]
 [0.72119797 0.27880203]
 [0.55263171 0.44736829]
 [0.06822515 0.93177485]
 [0.39955769 0.60044231]
 [0.87618759 0.12381241]
 [0.23969515 0.76030485]
 [0.61539201 0.38460799]
 [0.79151341 0.20848659]
 [0.8877596  0.1122404 ]
 [0.75337142 0.24662858]
 [0.65176768 0.34823232]
 [0.57482409 0.42517591]
 [0.94715975 0.05284025]
 [0.92482739 0.07517261]
 [0.74708131 0.25291869]
 [0.89515246 0.10484754]
 [0.69219086 0.30780914]
 [0.33048053 0.66951947]
 [0.17074256 0.82925744]
 [0.73025479 0.26974521]
 [0.35235716 0.64764284]
 [0.93693578 0.06306422]
 [0.92957976 0.07042024]
 [0.44938664 0.55061336]
 [0.45698458 0.54301542]
 [0.65676631 0.34323369]
 [0.46975102 0.53024898]
 [0.6774075  0.3225925 ]
 [0.74866974 0.25133026]
 [0.9476167  0.0523833 ]
 [0.29841806 0.70158194]
 [0.75337142 0.24662858]
 [0.05745997 0.94254003]
 [0.26679175 0.73320825]
 [0.53263559 0.46736441]
 [0.79084323 0.20915677]
 [0.18151876 0.81848124]
 [0.54241549 0.45758451]
 [0.33274643 0.66725357]
 [0.6596569  0.3403431 ]
 [0.77810597 0.22189403]
 [0.43579945 0.56420055]
 [0.2672556  0.7327444 ]
 [0.33382074 0.66617926]
 [0.73889507 0.26110493]
 [0.58094482 0.41905518]
 [0.13054959 0.86945041]
 [0.92977111 0.07022889]
 [0.89075641 0.10924359]
 [0.41059513 0.58940487]
 [0.31013851 0.68986149]
 [0.41324463 0.58675537]
 [0.54203477 0.45796523]
 [0.54852561 0.45147439]
 [0.10034846 0.89965154]
 [0.46378184 0.53621816]
 [0.22213414 0.77786586]
 [0.20054504 0.79945496]
 [0.65265235 0.34734765]
 [0.85911406 0.14088594]
 [0.68439893 0.31560107]
 [0.65977607 0.34022393]
 [0.74871927 0.25128073]
 [0.79036513 0.20963487]
 [0.26126977 0.73873023]
 [0.79823414 0.20176586]
 [0.86310087 0.13689913]
 [0.10703026 0.89296974]
 [0.60110676 0.39889324]
 [0.9917899  0.0082101 ]
 [0.44371222 0.55628778]
 [0.93876444 0.06123556]
 [0.21489517 0.78510483]
 [0.41059513 0.58940487]
 [0.30617289 0.69382711]
 [0.18980436 0.81019564]
 [0.49727273 0.50272727]
 [0.49283679 0.50716321]
 [0.70570683 0.29429317]
 [0.83093102 0.16906898]
 [0.85619825 0.14380175]
 [0.72548639 0.27451361]
 [0.80193515 0.19806485]
 [0.04736966 0.95263034]
 [0.66329842 0.33670158]
 [0.59048713 0.40951287]
 [0.42531546 0.57468454]
 [0.99351692 0.00648308]
 [0.44197351 0.55802649]
 [0.17198485 0.82801515]
 [0.92943169 0.07056831]
 [0.37932505 0.62067495]
 [0.97370051 0.02629949]
 [0.3171311  0.6828689 ]
 [0.28833763 0.71166237]
 [0.10013653 0.89986347]
 [0.16331913 0.83668087]
 [0.59068688 0.40931312]
 [0.29512636 0.70487364]
 [0.8809627  0.1190373 ]
 [0.86386361 0.13613639]
 [0.14480343 0.85519657]
 [0.07798197 0.92201803]
 [0.38862037 0.61137963]
 [0.76526216 0.23473784]
 [0.7942865  0.2057135 ]
 [0.98930482 0.01069518]
 [0.59048713 0.40951287]
 [0.58228898 0.41771102]
 [0.78800524 0.21199476]
 [0.38314034 0.61685966]
 [0.83152433 0.16847567]
 [0.55432828 0.44567172]
 [0.39347679 0.60652321]
 [0.52841587 0.47158413]
 [0.89952366 0.10047634]
 [0.92320659 0.07679341]
 [0.48161042 0.51838958]
 [0.65400381 0.34599619]
 [0.9023243  0.0976757 ]
 [0.23853764 0.76146236]
 [0.95088075 0.04911925]
 [0.46715629 0.53284371]
 [0.57866888 0.42133112]
 [0.3985371  0.6014629 ]
 [0.88666147 0.11333853]
 [0.60165961 0.39834039]
 [0.39140307 0.60859693]
 [0.87725524 0.12274476]
 [0.0725378  0.9274622 ]
 [0.6856125  0.3143875 ]
 [0.30247186 0.69752814]
 [0.72643555 0.27356445]
 [0.86626024 0.13373976]
 [0.085489   0.914511  ]
 [0.75350454 0.24649546]
 [0.26632973 0.73367027]
 [0.75337142 0.24662858]
 [0.44215715 0.55784285]
 [0.30181223 0.69818777]
 [0.93955482 0.06044518]
 [0.38654287 0.61345713]
 [0.676453   0.323547  ]
 [0.66238862 0.33761138]
 [0.52366904 0.47633096]]
next
[0.08340214 0.55613267 0.51722072 0.42358868 0.20582842 0.08574487
 0.57523191 0.81273571 0.75486183 0.29563643 0.30794042 0.71764873
 0.52867303 0.09034347 0.74618299 0.87074111 0.82933419 0.11534469
 0.54398369 0.67054226 0.20051812 0.29630432 0.86368804 0.46395793
 0.5543911  0.20784937 0.65092903 0.15140482 0.66888456 0.10934536
 0.18057659 0.77329311 0.61256256 0.09628689 0.31884284 0.11932552
 0.19393328 0.213592   0.35513986 0.42456071 0.37733562 0.70601999
 0.06332581 0.81499058 0.83558466 0.29531928 0.25743246 0.40951287
 0.57892326 0.6210519  0.86321055 0.25567985 0.93488359 0.52347272
 0.4387902  0.01986074 0.31325351 0.07103335 0.30062155 0.9749136
 0.08000611 0.74871769 0.1067394  0.87652638 0.08133187 0.954442
 0.83002349 0.22104248 0.79034592 0.09949579 0.25819967 0.36116657
 0.19108815 0.30587621 0.7099651  0.58992979 0.06867363 0.38790278
 0.79447695 0.70639527 0.14636322 0.14183417 0.6341788  0.06843919
 0.64776179 0.40573206 0.25007649 0.16520784 0.76010562 0.23265406
 0.17785696 0.06825283 0.77935625 0.06867363 0.37005964 0.07127021
 0.48544038 0.55417533 0.65172194 0.05623546 0.89564313 0.14710414
 0.240362   0.07022889 0.30055125 0.15521798 0.43611871 0.09118369
 0.06964006 0.61692002 0.27804096 0.69366853 0.56794459 0.72121101
 0.79851982 0.10325176 0.10279898 0.36540498 0.57839956 0.81163037
 0.46879944 0.0690594  0.58585045 0.68129394 0.240362   0.83512698
 0.0743754  0.25548676 0.67456746 0.0727013  0.06630801 0.28012753
 0.1954707  0.3693099  0.05515384 0.07238681 0.72317376 0.22528381
 0.22605916 0.01736202 0.17807461 0.90992522 0.23803566 0.18681084
 0.21894867 0.05771653 0.28291387 0.34889786 0.39068519 0.24330565
 0.75553599 0.53548774 0.02927093 0.18198368 0.0094723  0.03007115
 0.90027806 0.20543475 0.21894867 0.85522611 0.2465525  0.53855855
 0.40563845 0.06699609 0.76557184 0.84349072 0.91546263 0.03335522
 0.64949054 0.21210603 0.06181059 0.70181808 0.31097365 0.10484754
 0.01440618 0.48842428 0.94777004 0.75678395 0.39279673 0.49826346
 0.57448596 0.30171797 0.95662835 0.78561465 0.9332129  0.24984501
 0.63594827 0.04979937 0.01701589 0.14351101 0.51711003 0.25709369
 0.36735724 0.85754003 0.83092618 0.51494951 0.5092495  0.21790269
 0.59389971 0.62483068 0.27188173 0.10842478 0.2678671  0.48013256
 0.17025217 0.71635598 0.2272335  0.1705605  0.90268458 0.12815792
 0.14734527 0.35850866 0.17123383 0.25334324 0.01605614 0.86981954
 0.69418351 0.22217885 0.97464795 0.06867363 0.4379812  0.07586375
 0.22780796 0.07543782 0.57987053 0.29847502 0.07332675 0.24662858
 0.06498917 0.55185927 0.76632079 0.55792879 0.05506494 0.41027202
 0.2491541  0.36447921 0.22615754 0.47785109 0.40989242 0.50438843
 0.894365   0.79854295 0.34875837 0.06842646 0.03162193 0.3475291
 0.88915952 0.54791621 0.63251061 0.33904205 0.49681673 0.3136185
 0.44700609 0.07460545 0.32926489 0.3378302  0.41526471 0.53522905
 0.83908311 0.36049158 0.05249029 0.61789918 0.748824   0.44650692
 0.68839551 0.06843919 0.15714758 0.06873623 0.70454124 0.46139233
 0.34248941 0.09118369 0.92968043 0.27880203 0.44736829 0.93177485
 0.60044231 0.12381241 0.76030485 0.38460799 0.20848659 0.1122404
 0.24662858 0.34823232 0.42517591 0.05284025 0.07517261 0.25291869
 0.10484754 0.30780914 0.66951947 0.82925744 0.26974521 0.64764284
 0.06306422 0.07042024 0.55061336 0.54301542 0.34323369 0.53024898
 0.3225925  0.25133026 0.0523833  0.70158194 0.24662858 0.94254003
 0.73320825 0.46736441 0.20915677 0.81848124 0.45758451 0.66725357
 0.3403431  0.22189403 0.56420055 0.7327444  0.66617926 0.26110493
 0.41905518 0.86945041 0.07022889 0.10924359 0.58940487 0.68986149
 0.58675537 0.45796523 0.45147439 0.89965154 0.53621816 0.77786586
 0.79945496 0.34734765 0.14088594 0.31560107 0.34022393 0.25128073
 0.20963487 0.73873023 0.20176586 0.13689913 0.89296974 0.39889324
 0.0082101  0.55628778 0.06123556 0.78510483 0.58940487 0.69382711
 0.81019564 0.50272727 0.50716321 0.29429317 0.16906898 0.14380175
 0.27451361 0.19806485 0.95263034 0.33670158 0.40951287 0.57468454
 0.00648308 0.55802649 0.82801515 0.07056831 0.62067495 0.02629949
 0.6828689  0.71166237 0.89986347 0.83668087 0.40931312 0.70487364
 0.1190373  0.13613639 0.85519657 0.92201803 0.61137963 0.23473784
 0.2057135  0.01069518 0.40951287 0.41771102 0.21199476 0.61685966
 0.16847567 0.44567172 0.60652321 0.47158413 0.10047634 0.07679341
 0.51838958 0.34599619 0.0976757  0.76146236 0.04911925 0.53284371
 0.42133112 0.6014629  0.11333853 0.39834039 0.60859693 0.12274476
 0.9274622  0.3143875  0.69752814 0.27356445 0.13373976 0.914511
 0.24649546 0.73367027 0.24662858 0.55784285 0.69818777 0.06044518
 0.61345713 0.323547   0.33761138 0.47633096]
0.8406285072951739

In [12]:
# 梯度提升機預測檔 
gdbt.fit(train_X, train_Y)
gdbt_pred = gdbt.predict_proba(test_X)[:,1]
gdbt_score=gdbt.score(train_X,train_Y)
print(gdbt_score)
sub = pd.DataFrame({'PassengerId': ids, 'Survived': gdbt_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_gdbt.csv', index=False)

0.9506172839506173

In [13]:
# 隨機森林預測檔
rf.fit(train_X, train_Y)
rf_pred = rf.predict_proba(test_X)[:,1]
rf_score=rf.score(train_X,train_Y)
print(rf_score)
sub = pd.DataFrame({'PassengerId': ids, 'Survived': rf_pred})
sub['Survived'] = sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_rf.csv', index=False)

0.8529741863075196

# 作業
* 雖然同樣是混合泛化，分類預測其實與回歸預測有相當多的差異性，
因為鐵達尼預測的結果是 '生存/死亡'，輸出不是 0 就是 1  
因此要用權重混合時，需要以以機率的形式混合，因此我們在作業前幾格當中，先幫各位同學把預測值寫成了機率的形式  
(請同學把下列程式完成，並將結果提交到 Kaggle 網站看看結果)

* 但是光是這樣，分類問題的混合泛化就能比單模預測還要好嗎?  
已經快要期中考了，這裡請同學挑戰看看，還有沒有什麼方法可以改進混合泛化的結果?

In [14]:
# 混合泛化預測檔 
"""
Your Code Here
"""
ls_score=(ls_score*100)**30
gdbt_score=(gdbt_score*100)**30
rf_score=(rf_score*100)**30

ls_ratio=(ls_score)/(ls_score+gdbt_score+rf_score)
gdbt_ratio=(gdbt_score)/(ls_score+gdbt_score+rf_score)
rf_ratio=(rf_score)/(ls_score+gdbt_score+rf_score)
print(ls_ratio)
print(gdbt_ratio)
print(rf_ratio)

ls_ratio=0.3
gdbt_ratio=0.65
rf_ratio=0.05

blending_pred = lr_pred*ls_ratio  + gdbt_pred*gdbt_ratio + rf_pred*rf_ratio
sub = pd.DataFrame({'PassengerId': ids, 'Survived': blending_pred})
sub['Survived'] =  sub['Survived'].map(lambda x:1 if x>0.5 else 0) 
sub.to_csv('titanic_blending.csv', index=False)

0.023503129695481143
0.940098751805896
0.036398118498622976